travis:
  secure:
    BINSTAR_TOKEN: YsJGRdKJq69m2qB9sxDzrqwrngKWqwGk9/6PGRYzXrN8YTuy8klNSKO5YvykmG5fpQbT/nFtzN9T4TTXRFVlx/riV2d6zi5EQsOKUu6FirrwNQtc3omW00TKlfwOf3S3OoMzuue1+K+ldrGmA8f58E4xFYFpR6+WrZt9JA8PgGnDA7MgxX0poO/+oQX6ygk54CuVinJ66i/P9hpBMnSk2diC9+t5sZlKDlzwAdXXPksCeuVJ6KhOLCtlCnRFHgVErDhp52xBtymY4KkDyYaqeQF81rGTMRTbQqEJ3OS5YATmpS8SBLLXHZtYVt4UrkGb6e4c7WwjjTeUIGve5XYQlt5pOPnfxcr/Pg7dd8qIOCDg0KwM/Td0aNunfZ7E2j173T5e6aFCfk0BZYW9AiImtkBE2zy+FB+dTOwRX7rEowXYDW9Tuh02vgIt6BfJApzXYM2Pjs0OrcFv+jl7RpPhjSqa4AXmUSUwM1S2OA5TE0860PkdL4iXkpoa/GxKVTzPSRxILqPIDUbl8cy4z9qi5BPMHmEmEGT8lj5WphP28hwNosQ/E8g0i0yN8cKLTg/kqF85mqU4ITCZ2+LPhtAGm2O0aKWh+cDT9QXDuszh6R6+fKgQcjfquaKKqMdSUUIFS1sul1omQ3EUuIjrXAkj0kRW85vWFn+57025ZoWcf30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
